[build]
pre-build = [
  # Use HTTPS for package sources
  "apt-get update && apt-get install --assume-yes --no-install-recommends ca-certificates",
  "find /etc/apt/ -type f \\( -name '*.list' -o -name '*.sources' \\) -exec sed -i 's|http://|https://|g' {} +",

  # Configure APT retries and timeouts to handle network issues
  "echo 'Acquire::Retries \"3\";' > /etc/apt/apt.conf.d/80-retries",
  "echo 'Acquire::http::Timeout \"60\";' >> /etc/apt/apt.conf.d/80-retries",
  "echo 'Acquire::ftp::Timeout \"60\";' >> /etc/apt/apt.conf.d/80-retries",

  # rust-bindgen dependencies: llvm-dev libclang-dev (>= 10) clang (>= 10)
  # See: https://github.com/cross-rs/cross/wiki/FAQ#using-clang--bindgen for
  # recommended clang versions for the given cross and bindgen version.
  "apt-get update && apt-get install --assume-yes --no-install-recommends llvm-dev libclang-dev clang",
]

[build.env]
passthrough = ["JEMALLOC_SYS_WITH_LG_PAGE"]
