[build]
pre-build = [
  # Use HTTPS for package sources
  "apt-get update && apt-get install --assume-yes --no-install-recommends ca-certificates",
  "find /etc/apt/ -type f \\( -name '*.list' -o -name '*.sources' \\) -exec sed -i 's|http://|https://|g' {} +",

  # Configure APT retries and timeouts to handle network issues
  "echo 'Acquire::Retries \"3\";' > /etc/apt/apt.conf.d/80-retries",
  "echo 'Acquire::http::Timeout \"60\";' >> /etc/apt/apt.conf.d/80-retries",
  "echo 'Acquire::ftp::Timeout \"60\";' >> /etc/apt/apt.conf.d/80-retries",

  # rust-bindgen dependencies: llvm-dev libclang-dev (>= 10) clang (>= 10)
  # See: https://github.com/cross-rs/cross/wiki/FAQ#using-clang--bindgen for
  # recommended clang versions for the given cross and bindgen version.
  "apt-get update && apt-get install --assume-yes --no-install-recommends llvm-dev libclang-dev clang",
]

# Use Ubuntu 24.04 for both targets to get newer GLIBC that matches current Rust toolchain
[target.x86_64-unknown-linux-gnu]
image = "ubuntu:24.04"
pre-build = [
  "apt update",
  "apt install --yes gcc libclang-dev make",
]

[target.aarch64-unknown-linux-gnu]
image = "ubuntu:24.04"
pre-build = [
  "apt update",
  "apt install --yes gcc gcc-aarch64-linux-gnu libclang-dev make",
]

[target.aarch64-unknown-linux-gnu.env]
passthrough = [
  "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc",
]

[build.env]
passthrough = ["JEMALLOC_SYS_WITH_LG_PAGE"]
