name: Reusable Docker Build

on:
  workflow_call:
    inputs:
      make-target:
        description: 'Makefile target to run'
        required: true
        type: string
      profile:
        description: 'Cargo profile to use'
        required: false
        type: string
        default: 'release'

env:
  IMAGE_NAME: ${{ github.repository_owner }}/bera-reth
  DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/bera-reth
  DOCKER_USERNAME: ${{ github.actor }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker builder
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install arm64,amd64
          docker buildx create --use --name cross-builder

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build and push Docker image
        run: DOCKER_IMAGE_NAME=${{ env.DOCKER_IMAGE_NAME }} PROFILE=${{ inputs.profile }} make ${{ inputs.make-target }}