name: Docker

on:
  push:
    tags:
      - v*

jobs:
  docker-release-candidate:
    if: contains(github.ref, '-rc')
    uses: ./.github/workflows/docker-build.yml
    with:
      make-target: docker-build-push

  docker-latest:
    if: ${{ !contains(github.ref, '-rc') }}
    uses: ./.github/workflows/docker-build.yml
    with:
      make-target: docker-build-push-latest