name: Docker Git SHA

on:
  workflow_dispatch:

jobs:
  docker-git:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/docker-build.yml
    with:
      make-target: docker-build-push-git-sha